### Steps to remember
#### For classical
1. import modules
2. import data as a csv file
3. distinguish data and target that is , labeling
4. then define x and y axis with data and target
5. distribute them as train and test data
6. define model
7. fit the model
8. predict the using x_test
9. confusion matrix
10. classification report
11. predict different values

#### For quantum
1. import the required modules
2. define the adhoc_dimension, adhoc_feature_map
3. define sampler and kernel
4. define model that is QSVC
5. fit the model
6. confusion matrix
7. classifcation report
8. again predict with another data

In [21]:
%matplotlib inline

## CML

In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df_iris = pd.read_csv('iris.csv')
df_iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [24]:
iris_data = pd.DataFrame(df_iris, columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
iris_target = pd.DataFrame(df_iris, columns = ['species'])   
# iris_data
# iris_target

In [25]:
x = iris_data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = iris_target[['species']]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.30)
C = 1.0
csvm_model = SVC()
csvm_model.fit(x_train.values, y_train.values.ravel())
csvm_pred = csvm_model.predict(x_test.values)
print("Confusion matrix")
print(confusion_matrix(y_test,csvm_pred),'\n')
print('Classification report')
print(classification_report(y_test,csvm_pred))
print("Predict the flower type for data sepal (4,4,4,4) and Petal (4.4, 4.4)")
csvm_model.predict([[4.4, 4.4, 4.4, 4.4]])

Confusion matrix
[[21  0  0]
 [ 0 14  0]
 [ 0  1  9]] 

Classification report
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        21
  versicolor       0.93      1.00      0.97        14
   virginica       1.00      0.90      0.95        10

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

Predict the flower type for data sepal (4,4,4,4) and Petal (4.4, 4.4)


array(['virginica'], dtype=object)

## QML

In [26]:
from qiskit.circuit.library import ZZFeatureMap
from qiskit.primitives import Sampler
from qiskit_algorithms.state_fidelities import ComputeUncompute
from qiskit_machine_learning.kernels import FidelityQuantumKernel
adhoc_dimension = 2
adhoc_feature_map = ZZFeatureMap(feature_dimension = adhoc_dimension, reps = 2,entanglement = "linear")
# Classical data is encoded into qubit angles
sampler = Sampler()
fidelity = ComputeUncompute(sampler = sampler)
adhoc_kernel = FidelityQuantumKernel(fidelity = fidelity, feature_map = adhoc_feature_map)

In [27]:
from qiskit_machine_learning.algorithms import QSVC

qsvm_model = QSVC(quantum_kernel = adhoc_kernel)
qsvm_model.fit(x_train, y_train.values.ravel())
qsvm_pred = qsvm_model.predict(x_test)
print("Confusion matrix")
print(confusion_matrix(y_test,qsvm_pred))
print("Classification report")
print(classification_report(y_test, qsvm_pred))
print("Predict the flower type for data sepal (4.4,4.4) and petal (4.4, 4.4)")
qsvm_model.predict([[4.4,4.4,4.4,4.4]])

Confusion matrix
[[17  2  2]
 [ 0 13  1]
 [ 1  3  6]]
Classification report
              precision    recall  f1-score   support

      setosa       0.94      0.81      0.87        21
  versicolor       0.72      0.93      0.81        14
   virginica       0.67      0.60      0.63        10

    accuracy                           0.80        45
   macro avg       0.78      0.78      0.77        45
weighted avg       0.81      0.80      0.80        45

Predict the flower type for data sepal (4.4,4.4) and petal (4.4, 4.4)


array(['virginica'], dtype=object)