In [1]:
%matplotlib inline

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_iris = pd.read_csv('iris.csv')

In [4]:
iris_data = pd.DataFrame(df_iris, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'])
iris_target = pd.DataFrame(df_iris, columns=['Species'])

In [5]:
x = iris_data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris_target[["Species"]]
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30)
C = 1.0
csvm_model = SVC()
csvm_model.fit(x_train.values, y_train.values.ravel())
csvm_pred = csvm_model.predict(x_test.values)
print("Confusion Matrix")
print(confusion_matrix(y_test, csvm_pred))
print("Classification Report")
print(classification_report(y_test, csvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
csvm_model.predict([[4.4,4.4,4.4,4.4]])

Confusion Matrix
[[13  0  0]
 [ 0 14  0]
 [ 0  0 18]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      1.00      1.00        14
 Iris-virginica       1.00      1.00      1.00        18

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-virginica'], dtype=object)

In [6]:
from qiskit.circuit.library import ZZFeatureMap
from qiskit.primitives import Sampler
from qiskit_algorithms.state_fidelities import ComputeUncompute
from qiskit_machine_learning.kernels import FidelityQuantumKernel
adhoc_dimension=2
adhoc_feature_map = ZZFeatureMap(feature_dimension=adhoc_dimension, reps=2, entanglement="linear") 
#classical data is encoded into qubit angles
sampler = Sampler()
fidelity = ComputeUncompute(sampler=sampler)
adhoc_kernel = FidelityQuantumKernel(fidelity=fidelity, feature_map=adhoc_feature_map)

In [7]:
from qiskit_machine_learning.algorithms import QSVC

qsvm_model = QSVC(quantum_kernel=adhoc_kernel)
qsvm_model.fit(x_train, y_train.values.ravel())
qsvm_pred = qsvm_model.predict(x_test)
print("Confusion Matrix")
print(confusion_matrix(y_test, qsvm_pred))
print("Classification Report")
print(classification_report(y_test, qsvm_pred))
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)")
qsvm_model.predict([[4.4,4.4,4.4,4.4]])

Confusion Matrix
[[10  2  1]
 [ 1 10  3]
 [ 3  0 15]]
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       0.71      0.77      0.74        13
Iris-versicolor       0.83      0.71      0.77        14
 Iris-virginica       0.79      0.83      0.81        18

       accuracy                           0.78        45
      macro avg       0.78      0.77      0.77        45
   weighted avg       0.78      0.78      0.78        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4)


array(['Iris-versicolor'], dtype=object)