### CML

In [35]:
%matplotlib inline

In [36]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
df_toy = pd.read_csv("toy.csv")
df_toy

toy name  toy height  toy width    toy color    toy shape  \
0          Teddy Bear          10          8        Brown         Soft   
1     Building Blocks           5          5     Colorful         Cube   
2                Doll          12          6         Pink      Plastic   
3             Toy Car           8         12          Red        Metal   
4              Puzzle           7          7         Blue  Rectangular   
5      Stuffed Animal          14         10        White       Fluffy   
6  Remote Control Car           9         15        Black      Plastic   
7        Play Kitchen          18         12  Multi-color  Interactive   
8       Action Figure           6          4        Green      Plastic   
9          Board Game          12         12       Yellow       Square   

   toy cost gifted by baby gender  baby age  liked  
0        15   Grandma      Female        18      1  
1        20   Parents        Male        24      0  
2        18      Aunt      Female        12      0  
3        12     Uncle        Male        15      1  
4        25   Grandpa        Male        20      1  
5        30    Friend      Female        22      1  
6        40   Parents        Male        14      0  
7        35      Aunt      Female        30      1  
8        10     Uncle        Male        10      1  
9        28   Grandma        Male        16      1

In [38]:
toy_data = pd.DataFrame(df_toy, columns = ['toy height', 'toy width','toy cost','baby age'])
toy_target = pd.DataFrame(df_toy, columns = ['liked'])
# toy_data
# toy_target
# print(y['liked'].unique())
# print(y.shape)

In [40]:
x = toy_data[['toy height', 'toy width', 'toy cost','baby age']]
y = toy_target[['liked']]
# Check and reshape target variable
# print(y['liked'].unique())
y = y.values.reshape(-1, 1)
print(y.shape)
# Check the shape of input features
print(x.shape)
x_train, x_test,y_train,y_test = train_test_split(x,y,train_size = 0.30)
C = 1.0
svm_model = SVC()
svm_model.fit(x_train.values, y_train.ravel())
svm_pred = svm_model.predict(x_test.values)
print("Confusion matrix")
print(confusion_matrix(y_test, svm_pred))
print('classification report')
print(classification_report(y_test,svm_pred, zero_division = 1))
print('Predict if baby likes it or not')
svm_model.predict([[9,9,30,15]])

(10, 1)
(10, 4)
Confusion matrix
[[0 2]
 [0 5]]
classification report
              precision    recall  f1-score   support

           0       1.00      0.00      0.00         2
           1       0.71      1.00      0.83         5

    accuracy                           0.71         7
   macro avg       0.86      0.50      0.42         7
weighted avg       0.80      0.71      0.60         7

Predict if baby likes it or not


array([1])

### QML

In [42]:
from qiskit.circuit.library import ZZFeatureMap
from qiskit.primitives import Sampler
from qiskit_algorithms.state_fidelities import ComputeUncompute
from qiskit_machine_learning.kernels import FidelityQuantumKernel
adhoc_dimension = 2
adhoc_feature_map = ZZFeatureMap(feature_dimension = adhoc_dimension, reps = 2,entanglement = "linear")
# Classical data is encoded into qubit angles
sampler = Sampler()
fidelity = ComputeUncompute(sampler = sampler)
adhoc_kernel = FidelityQuantumKernel(fidelity = fidelity, feature_map = adhoc_feature_map)

In [47]:
from qiskit_machine_learning.algorithms import QSVC

qsvm_model = QSVC(quantum_kernel = adhoc_kernel)
qsvm_model.fit(x_train, y_train.ravel())
qsvm_pred = qsvm_model.predict(x_test)
print("Confusion matrix")
print(confusion_matrix(y_test,qsvm_pred))
print("Classification report")
print(classification_report(y_test, qsvm_pred,zero_division = 1))
print("Predict if baby likes it or not")
qsvm_model.predict([[9,9,30,15]])

Confusion matrix
[[0 2]
 [0 5]]
Classification report
              precision    recall  f1-score   support

           0       1.00      0.00      0.00         2
           1       0.71      1.00      0.83         5

    accuracy                           0.71         7
   macro avg       0.86      0.50      0.42         7
weighted avg       0.80      0.71      0.60         7

Predict if baby likes it or not


array([1])